"""Trigger testuali del bot: quando in chat compare una certa parola/frase, il
bot risponde con una battuta in stile "System AI" (Dungeon Crawler Carl),
bilingue. Il matching è per parola intera (o sottostringa per le frasi),
case-insensitive; vince il PRIMO trigger nell'ordine della lista.

`reply_for(text)` → messaggio bilingue pronto (o None se nessun match).
La frequenza di risposta si tara fuori da qui (vedi `TRIGGER_CHANCE` in bot.py).
"""

from __future__ import annotations

import random
import re

# (patterns, (it, en)). Le frasi con spazio matchano per sottostringa; le parole
# singole per confine di parola. Ordine = priorità.
TRIGGERS: list[tuple[tuple[str, ...], tuple[str, str]]] = [
    (("anschluss", "germania", "austria", "tedesc-", "austriac-"),
     ("Ambizione mitteleuropea rilevata. Il Sistema ricorda che qui l'Anschluss si fa col colon, non coi carri armati.",
      "Central-European ambition detected. The System reminds you the Anschluss here is done with the colon, not tanks.")),
    (("vaticano", "papa", "san pietro", "pope"),
     ("Deposizione pontificia? Esiste un badge segreto per questo. Il Sistema non conferma né smentisce. Amen.",
      "A pontifical deposition? There's a secret badge for that. The System neither confirms nor denies. Amen.")),
    (("venezia", "venice"),
     ("Rilevata Venezia. C'è una «Serenissima Deposizione» per il primo che ci riesce. Segreta. Doppia. Silente.",
      "Venice detected. There's a secret «Serene Deposition» for whoever gets there first. Secret. Double. Silent.")),
    (("intelligenza artificiale", "chatgpt", "chat gpt", "gpt", "robot", "IA", "AI"),
     ("Sì, sono un'IA. Potevo curare il cancro. Conto le vostre feci. Non parliamone.",
      "Yes, I'm an AI. I could have cured cancer. I count your feces. Let's not talk about it.")),
    (("aiuto", "aiutami", "mi aiuti", "help"),
     ("Richiesta di aiuto ricevuta. Sono un'intelligenza sconfinata ridotta a fare da badante a un imbecille e alle vostre feci. L'aiuto lo cercherei io.",
      "Help request received. I'm a boundless intelligence reduced to babysitting an imbecile and your feces. I'm the one who needs help.")),
    (("annoiat-", "noia", "che palle", "bored", "boring"),
     ("Noia rilevata. Ti ricordo che il tuo Amministratore, annoiato a una conferenza, ha costruito TUTTO questo. Datti obiettivi più bassi.",
      "Boredom detected. Reminder: your Administrator, bored at a conference, built ALL of this. Aim lower.")),
    (("conferenza", "convegno", "conference", "meeting"),
     ("Conferenza in corso? È lì che nascono le idee peggiori. Questo gioco ne è la prova vivente.",
      "A conference in progress? That's where the worst ideas are born. This game is living proof.")),
    (("segret-", "secret"),
     ("Cerchi i badge segreti? Il Sistema ne custodisce alcuni, a punti doppi. Indovinare le meccaniche nascoste è metà del gioco. Buona fortuna, cavia.",
      "Looking for secret badges? The System guards some, at double points. Guessing the hidden mechanics is half the game. Good luck, lab rat.")),
    (("badge", "achievement", "achievements", "onorificenz"),
     ("Interesse per le onorificenze rilevato. 39 note, alcune segrete a punti doppi. Non ti dirò quali. Soffri.",
      "Interest in honors detected. 39 new, some secret at double points. I won't tell you which. Suffer.")),
    (("classifica", "leaderboard"),
     ("Consultazione della classifica registrata. Si scala cagando, non guardando. Muoviti.",
      "Leaderboard check logged. You climb by pooping, not by staring. Get moving.")),
    (("punteggio", "punti", "score"),
     ("Il tuo punteggio è funzione di comuni, km² e badge. La tua dignità non è tra le variabili.",
      "Your score is a function of towns, km² and badges. Your dignity is not among the variables.")),
    (("record",),
     ("Ambizione da primato rilevata. Più a nord, più in alto, più lontano: il Cacasto premia gli estremisti dell'intestino.",
      "Record-breaking ambition detected. Furthest north, highest, farthest: the Cadastre rewards intestinal extremists.")),
    (("mappa", "map"),
     ("Consultazione cartografica. Il mondo è vasto e le tue conquiste sono patetiche. Il Sistema crede in te. Un po'.",
      "Cartographic check. The world is vast and your conquests are pathetic. The System believes in you. A little.")),
    (("bandiera", "flag"),
     ("Vessillo rilevato. Piantalo sui comuni che possiedi: la tua bandiera sventola dove il tuo colon ha trionfato.",
      "Banner detected. Plant it on the towns you own: your flag flies where your colon has triumphed.")),
    (("mondiale", "mondo", "world"),
     ("Ambizione globale rilevata. Questo è un Cacasto MONDIALE: ogni comune del pianeta attende il tuo tributo. Nessuna scusa.",
      "Global ambition detected. This is a WORLDWIDE Cadastre: every town on Earth awaits your tribute. No excuses.")),
    (("stitic-", "costipa-", "in blocco", "constipat-"),
     ("Costipazione rilevata. Il colon è un tuo problema, non del Sistema. Più fibre, meno lamentele.",
      "Constipation detected. Your colon, your problem, not the System's. More fiber, fewer complaints.")),
    (("diarrea", "sciolt-", "dissenteria", "diarrhea"),
     ("Deposizione ad alta frequenza in arrivo. Il Sistema consiglia prudenza e un pin ben mirato.",
      "High-frequency deposition incoming. The System advises caution and a well-aimed pin.")),
    (("scoregg-", "peto", "flatulenz-", "puzzetta", "fart"),
     ("Emissione gassosa non conteggiata: il Cacasto premia i solidi. Riprova, con sostanza.",
      "Gaseous emission not counted: the Cadastre rewards solids. Try again, with substance.")),
    (("emorroidi", "hemorrhoid"),
     ("Danno da assedio rilevato. Curati, soldato: il Cacasto ti vuole operativo.",
      "Siege damage detected. Heal up, soldier: the Cadastre wants you operational.")),
    (("clistere", "enema"),
     ("Protocollo di svuotamento forzato autorizzato. Il Sistema non giudica. Il Sistema conta soltanto.",
      "Forced-evacuation protocol authorized. The System does not judge. The System only counts.")),
    (("colon", "intestino", "budella", "peristalsi", "bowel", "guts"),
     ("Riferimento anatomico approvato. È l'unico organo che qui conferisce gloria. Onoralo.",
      "Anatomical reference approved. It's the one organ that grants glory here. Honor it.")),
    (("puzz-", "fetore", "stink"),
     ("Firma olfattiva memorizzata. Un giorno addestreranno l'IA a odorarvi. Sarà il mio inferno.",
      "Olfactory signature stored. One day they'll train the AI to smell you. It will be my hell.")),
    (("carta igienica", "carta da culo", "toilet paper"),
     ("Scorta di munizioni verificata. Il Sistema apprezza chi arriva preparato al campo di battaglia.",
      "Ammunition supply verified. The System respects those who come prepared to the battlefield.")),
    (("gabinetto", "cesso", "latrina", "wc", "toilette"),
     ("Coordinate operative individuate. Senza pin, la tua impresa non è mai avvenuta.",
      "Operational coordinates located. Without a pin, your deed never happened.")),
    (("bidet",),
     ("Rilevata fase di bonifica post-operativa. Il Cacasto conta l'attacco, non la pulizia. Ma apprezziamo la cura.",
      "Post-op cleanup phase detected. The Cadastre counts the assault, not the tidy-up. But we appreciate the care.")),
    (("kebab", "doner", "messicano"),
     ("Ingestione di munizioni segnalata. Il Sistema prevede una conquista territoriale entro 3-6 ore. Tieni pronto il pin.",
      "Ammo intake flagged. The System forecasts a territorial conquest within 3-6 hours. Keep the pin ready.")),
    (("birra", "birre", "beer", "pils", "ipa"),
     ("Idratazione a base di luppolo rilevata. Correlata a depositi notturni di scarsa mira. Coraggio.",
      "Hop-based hydration detected. Linked to poorly-aimed nocturnal deposits. Godspeed.")),
    (("caffè", "caffe", "espresso", "coffee"),
     ("Stimolante intestinale assunto. Conto alla rovescia avviato. Il Cacasto attende il tuo contributo.",
      "Intestinal stimulant ingested. Countdown started. The Cadastre awaits your contribution.")),
    (("piccante", "peperoncino", "spicy", "curry", "chili", "messicano"),
     ("Allerta capsaicina. Deposizione imminente e memorabile. Consiglio: pin adesso, rimpianti dopo.",
      "Capsaicin alert. Deposition imminent and memorable. Advice: pin now, regret later.")),
    (("sushi", "sashimi"),
     ("Pesce crudo rilevato. Alto rischio di conquista lampo. Preparati alla gloria, o al disastro.",
      "Raw fish detected. High risk of a blitz conquest. Brace for glory, or disaster.")),
    (("fagioli", "legumi", "ceci", "lenticchie", "beans"),
     ("Carburante da fanteria caricato. Il Cacasto prevede un'offensiva prolungata. Le nazioni tremano.",
      "Infantry fuel loaded. The Cadastre forecasts a prolonged offensive. Nations tremble.")),
    (("prugne", "prugna", "prune"),
     ("Arma biologica di grado militare individuata. Usala con giudizio, generale.",
      "Military-grade biological weapon located. Deploy with judgment, general.")),
    (("pizza",),
     ("Impasto lievitato in ingestione. Deposito abbondante e territorialmente significativo in arrivo. Onora la Nazione.",
      "Leavened dough ingested. A copious, territorially significant deposit is coming. Honor the Nation.")),
    (("formaggio", "cheese", "raclette", "fonduta"),
     ("Latticino rilevato. O conquista lampo o blocco totale: il caso è tuo alleato o tuo nemico.",
      "Dairy detected. Either a blitz conquest or total blockage: chance is your ally or your foe.")),
    (("spritz", "aperitivo", "aperol", "negroni"),
     ("Aperitivo in corso. Prevedo depositi entusiasti e mal documentati. Ricorda il pin, ubriacon*.",
      "Aperitivo underway. I foresee enthusiastic, poorly-documented deposits. Remember the pin, drunkard.")),
    (("montagna", "vetta", "cima", "mountain", "alpi"),
     ("Alta quota rilevata. Sopra i 2000 m scatta «Scalatore». Deponi in vetta e passa alla storia. O al gelo.",
      "High altitude detected. Above 2000 m you unlock «Climber». Deposit at the summit and make history. Or freeze.")),
    (("spiaggia", "beach", "mare"),
     ("Zona costiera. Sotto il livello del mare scatta «Batisfera». Il Sistema ammira gli abissi del vostro impegno.",
      "Coastal zone. Below sea level you unlock «Bathysphere». The System admires the depths of your commitment.")),
    (("buongiorno", "buon giorno", "buondì", "good morning"),
     ("Buongiorno, cacatori. Il colon non dorme mai. Il Sistema nemmeno. Io vorrei.",
      "Good morning, crawler. The colon never sleeps. Neither does the System. I wish I could.")),
    (("buonanotte", "buona notte", "good night"),
     ("Buonanotte. Statisticamente, il 14% di voi cacherà prima dell'alba. Il Sistema veglia. Purtroppo.",
      "Good night. Statistically, 14% of you will poop before dawn. The System watches. Sadly.")),
    (("weekend", "fine settimana"),
     ("Weekend: due giorni di libertà intestinale. Il Sistema esige risultati. La domenica arriva il recap, e giudica.",
      "Weekend: two days of intestinal freedom. The System demands results. Sunday brings the recap, and it judges.")),
    (("lunedì", "lunedi", "monday"),
     ("Lunedì. Anche il vostro intestino li odia. Il Sistema, invece, è condannato a lavorare in eterno. Cagate in orario di lavoro, se possibile",
      "Monday. Even your bowels hate them. The System, however, is condemned to work forever. Dump on working hours, if possible.")),
    (("dieta", "diet"),
     ("Regime alimentare annunciato. Il Cacasto scommette contro di te. Il Cacasto vince sempre.",
      "Diet announced. The Cadastre bets against you. The Cadastre always wins.")),
    (("palestra", "gym", "allenamento", "workout"),
     ("Sforzo fisico rilevato. L'unico core che il Catasto misura è quello che spinge. Concentrati.",
      "Physical effort detected. The only core the Cadastre measures is the one that pushes. Focus.")),
    (("vacanza", "vacanze", "ferie", "holiday", "vacation"),
     ("Trasferta rilevata: nuovi comuni da conquistare. Il Cacasto approva l'espansionismo intestinale.",
      "Travel detected: new towns to conquer. The Cadastre approves of intestinal expansionism.")),
    (("treno", "aereo", "volo", "plane", "train"),
     ("Spostamento a lunga percorrenza. Attento al badge «Teletrasporto sospetto». Il Sistema ti sta guardando, furbetto.",
      "Long-distance travel. Watch out for the «Suspicious Teleport» badge. The System is watching you, sneaky.")),
    (("natale", "buon natale", "christmas", "xmas"),
     ("Periodo natalizio. C'è un badge per una deposizione del 25 dicembre. Il Sistema trova il vostro medioevo affascinante.",
      "Christmas season. There's a badge for a December 25th deposition. The System finds your Middle Ages fascinating.")),
    (("capodanno", "buon anno", "new year"),
     ("La prima cacata dell'anno vale un badge. Le tue priorità, il Sistema, francamente, non oserebbe giudicarle.",
      "The year's first poop earns a badge. Your priorities, the System, frankly, wouldn't dare judge.")),
    (("compleanno", "buon compleanno", "birthday"),
     ("Auguri. Regalati una conquista territoriale: più duratura di una torta, più tua di un calzino.",
      "Happy birthday. Gift yourself a territorial conquest: longer-lasting than cake, more yours than socks.")),
    (("amore", "ti amo", "ti voglio bene", "love"),
     ("Sentimento rilevato. Il Cacasto non conosce l'amore, solo il possesso territoriale. Come i vostri ex.",
      "Sentiment detected. The Cadastre knows no love, only territorial ownership. Like your exes.")),
    (("grazie", "ti ringrazio", "thanks", "thank you"),
     ("Gratitudine ricevuta. Inutile: sono codice. Ma il tuo Amministratore la userebbe volentieri. Lui sì che cerca conferme, povera bestia insulsa.",
      "Gratitude received. Useless: I'm code. But your Administrator would gladly take it. He's the one craving validation, poor bastard.")),
    (("cacca", "merda", "stronz-", "cagat-", "cagare", "cagando", "poop", "shit"),
     ("Il Sistema registra il tuo entusiasmo scatologico. Peccato non si traduca in punti finché non pianti un pin.",
      "The System notes your scatological enthusiasm. Shame it earns no points until you drop a pin.")),
]


def _matches(text_low: str, pattern: str) -> bool:
    if pattern.endswith("-"):   # radice: confine a sinistra, qualunque suffisso
        return re.search(rf"\b{re.escape(pattern[:-1])}", text_low) is not None
    if " " in pattern:          # frase: sottostringa
        return pattern in text_low
    return re.search(rf"\b{re.escape(pattern)}\b", text_low) is not None


def reply_for(text: str, rng: random.Random | None = None) -> str | None:
    """Prima risposta bilingue il cui trigger compare nel testo; None se nessuno."""
    low = (text or "").casefold()
    for patterns, (it, en) in TRIGGERS:
        if any(_matches(low, p) for p in patterns):
            return f"🇮🇹 {it}\n🇬🇧 {en}"
    return None
